In [3]:
import numpy as np

# 데이터 생성 --------------------------------
np.random.seed(seed=1)  # 난수를 고정
N = 100                                   # 데이터의 수
K = 3                                         # 분포 수

T3 = np.zeros((N, 3), dtype=np.uint8)
X  = np.zeros((N, 2))

Mu = np.array([[-.5, -.5], [.5, 1.0], [1, -.5]])  #  분포의 중심
Sig = np.array([[.7, .7], [.8, .3], [.3, .8]])        #  분포의 분산
Pi  =  np.array([0.4, 0.8, 1])                             # (A) 각 분포에 대한 비율 0.4 0.8 1

for i in range(N):
    wk = np.random.rand()
    for k in range(K): # (B)
        if wk < Pi[k]:
            T3[i, k] = 1
            break
    for k in range(2):
        X[i, k] = (np.random.randn() * Sig[T3[i, :] == 1, k] + Mu[T3[i, :] == 1, k])


[[0.    0.006 0.994]
 [0.965 0.033 0.001]
 [0.925 0.07  0.005]
 [0.    0.    1.   ]
 [0.019 0.126 0.856]]


In [14]:
def  logistic3(x0, x1, w):
    # K = 3 # 이 줄 없어도 됨
    # n = len(x1) # 이 줄 없어도 됨
    # y = np.zeros((K, n)) # shape(3,5) # 이 줄 없어도 됨
    w = w.reshape((3, 3))
    x = np.array([x0, x1, np.ones_like(x0)]) # shape(3,5)
    y = np.exp(w.dot(x)) # shape(3,3) X shape(3,5) = shape(3,5)
    wk = np.sum(y, axis=0) # shape(5)
    
    return (y / wk).T # shape(3,5)/shape(5) = shape(3,5)  >>>  shape(5,3)


# test ---
W = np.array([1, 2, 3, 4 ,5, 6, 7, 8, 9])
y = logistic3(X[:5, 0], X[:5, 1], W)
print(np.round(y, 3))

[[0.    0.006 0.994]
 [0.965 0.033 0.001]
 [0.925 0.07  0.005]
 [0.    0.    1.   ]
 [0.019 0.126 0.856]]
