#### 모듈 불러오기

In [9]:
import numpy as np

#### 연속된 벡터 생성

In [18]:
print(np.arange(10))
print(np.arange(10, 15))
print(np.arange(10, 15, 0.5))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]


#### 복사 주의점

In [20]:
a = np.arange(5)
b = a
b[0] = 99
print(a)

a = np.arange(5)
b = a.copy()
b[0] = 99
print(a)

[99  1  2  3  4]
[0 1 2 3 4]


#### 모양같은 행렬 만들기

In [21]:
a = np.arange(12).reshape(3,4)
b = np.zeros(a.shape)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 행렬연산

In [34]:
shape = (2,3)
a = np.full(shape, 12)
print(a)
b = np.full(shape, 3)
print(b)

[[12 12 12]
 [12 12 12]]
[[3 3 3]
 [3 3 3]]


#### 행렬에 스칼라연산

In [35]:
print("a + 1 = ")
print(a + 1)
print("a * 3 = ")
print(a * 3)

a + 1 = 
[[13 13 13]
 [13 13 13]]
a * 3 = 
[[36 36 36]
 [36 36 36]]


#### 행렬에 행렬연산

In [36]:
print("a + b = ")
print(a + b)
print("a * b = ")
print(a * b)

a + b = 
[[15 15 15]
 [15 15 15]]
a * b = 
[[36 36 36]
 [36 36 36]]


#### 행렬에 함수 적용

In [63]:
def func(s):
    return s * 2

print(func(b))

[[6 6 6]
 [6 6 6]]


#### 행렬곱

In [43]:
c = b.T # 전치행렬
print(a)
print(c)
print(a.dot(c))

[[12 12 12]
 [12 12 12]]
[[3 3]
 [3 3]
 [3 3]]
[[108 108]
 [108 108]]


#### 슬라이싱

In [60]:
a = np.arange(36).reshape(6,6)
print(a)
print(a[3:, 3:])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[21 22 23]
 [27 28 29]
 [33 34 35]]


#### 배열안 조건 적용하기

In [59]:
a = np.random.random([3,4]).round(2)
print(a)
a[a>=0.5] = 1
a[a<0.5] = 0
print(a)

[[0.79 0.36 0.41 0.67]
 [0.18 0.93 0.48 0.85]
 [0.29 0.45 0.14 0.58]]
[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 0. 1.]]


#### numpy에서 지원하는 함수사용

In [66]:
a = np.random.randn(3,4).round(2) # 표준정규분포
print(a)

[[-0.99 -0.47  0.67 -1.77]
 [-1.96 -1.97 -0.48  1.2 ]
 [-0.3  -0.7   0.2   0.49]]


#### 평균

In [68]:
print(np.mean(a).round(2))

-0.51


#### 합

In [75]:
print(np.sum(a).round(2))
print(np.sum(a, axis=0).round(2))

-6.08
[-3.25 -3.14  0.39 -0.08]


#### 표준편차

In [76]:
print(np.std(a).round(2))

1.0


In [84]:
v = np.array([[1,2,3],[4,5,6]])
print(v[1:,1:])

[[5 6]]
